config/routes.rb
Rails.application.routes.draw do

  get 'creations/new'

  root 'static_pages#home'

  resources :users
  resources :events

  get 'static_pages/home'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'

  #get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/reset', to: 'users#reinitialize'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creation.rb
class Creation < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :registrations
	has_many :users, through: :registrations

	before_save { self.title = title.titleize }
  before_save { self.location = location.titleize }
  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :date, presence: true
  validates :location, presence: true, length: { minimum: 2, maximum: 100 }

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :creations
  has_many :events, through: :creations

  before_save { self.email = email.downcase }
  before_save { self.last_name = last_name.upcase }
  #validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, presence: true, length: { minimum: 2, maximum: 100 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 100 }
  validates :email, presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

    class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                          BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/creations_controller.rb
class CreationsController < ApplicationController

  def new
    @creation = Creation.new
  end

  def create
    @creation = Creation.new(creation_params)
    if @creation.save
      log_in @creation
      flash[:success] = "Creation successfully created!"
      redirect_to @creation
    else
      render 'new'
    end
  end

end


=begin
u = User.new; u.save
e = Event.new ; e.save

c = u.creations.new
c.event = e
c.save
=end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    if logged_in?
      @event = Event.new
    else
      redirect_to login_path
    end
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user.first_name+" "+current_user.last_name
    if @event.save
      flash[:success] = "Event successfully created!"
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    flash[:success] = "Event successfully updated!"
    redirect_to event_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Event successfully deleted!"
    redirect_to user_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :date)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to EventBrite Revamp"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:success] = "Profile updated!"
    redirect_to user_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Profile successfully deleted!"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creations_helper.rb
module CreationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/creations/new.html.erb
<h1>Creations#new</h1>
<p>Find me in app/views/creations/new.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit My Event</h1>

<p style="color:red;">All fields are required.</p>

<%= form_for @event do |f| %>

  <div class="form-group">

    <label>Title<span style="color:red;">*</span></label>

    <%= f.text_field :title, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Date<span style="color:red;">*</span></label>

    <%= f.date_field :date, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Location<span style="color:red;">*</span></label>

    <%= f.text_field :location, class: 'form-control' %>

  </div>

  <div class="form-group">

    <button type="submit">Modify Event</button>

  </div>

<% end %>

app/views/events/index.html.erb
<h1>All Events</h1>

<% @events.each do |event| %>

  <p><%= event.title %></p>
  <p><a href="<%= event_path(event.id) %>" class="btn btn-primary">Show Event</a></p>

<% end %>

<p><a href="<%= new_event_path %>" class="btn btn-default">Add New Event</a></p>

app/views/events/new.html.erb
<h1>Create A New Event</h1>

<p style="color:red;">All fields are required.</p>

<%= form_for @event do |f| %>

  <div class="form-group">

    <label>Title<span style="color:red;">*</span></label>

    <%= f.text_field :title, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Date<span style="color:red;">*</span></label>

    <%= f.date_field :date, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Location<span style="color:red;">*</span></label>

    <%= f.text_field :location, class: 'form-control' %>

  </div>

  <div class="form-group">

    <button type="submit">Create Event</button>

  </div>

<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<p>Date: <%= @event.date.strftime("%d/%m/%Y") %></p>
<p>Location: <%= @event.location %></p>
<p>Created by: <%= @event.creator %></p>

<p><a href="<%= edit_event_path %>" class="btn btn-primary">Edit my event</a></p>

<p><a href="<%= @event %>" class="btn btn-danger" data-confirm="Sure about this?" data-method="DELETE">Delete my event</a></p>

<p><a href="<%= root_path %>" class="btn btn-default">Back To Home</a></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Powered by <a href="http://simwyck.com/">SimWyck</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "EventBrite Da Best", root_path %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Profile", current_user %></li>
        <% else %>
          <li><%= link_to "Register", signup_path %></li>
        <% end %>
        <% if logged_in? %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLike</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
     <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>EventBrite Homepage</h1>
<p>Welcome to the best event app on THE internet!</p>
<p><%= link_to "View all events", events_path %></p>

app/views/users/edit.html.erb
<h1>Edit My Account</h1>

<p style="color:red;">All fields are required.</p>

<%= form_for @user do |f| %>

  <div class="form-group">

    <label>First Name<span style="color:red;">*</span></label>

    <%= f.text_field :first_name, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Last Name<span style="color:red;">*</span></label>

    <%= f.text_field :last_name, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Email<span style="color:red;">*</span></label>

    <%= f.text_field :email, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Pasword<span style="color:red;">*</span></label>

    <%= f.password_field :password, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Confirm Password<span style="color:red;">*</span></label>

    <%= f.password_field :password_confirmation, class: 'form-control' %>

  </div>

  <div class="form-group">

    <button type="submit">Save</button>

  </div>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<h2>Warning: For admins only</h2>

<% @users.each do |user| %>

  <p><%= user.email %></p>
  <p><%= user.first_name %> <%= user.last_name %></p>
  <p><a href="<%= user_path(user.id) %>" class="btn btn-primary">Show User</a></p>

<% end %>

<p><a href="<%= new_user_path %>" class="btn btn-default">Add New User</a></p>

app/views/users/new.html.erb
<h1>Create A New Account</h1>

<p style="color:red;">All fields are required.</p>

<%= form_for @user do |f| %>

  <div class="form-group">

    <label>First Name<span style="color:red;">*</span></label>

    <%= f.text_field :first_name, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Last Name<span style="color:red;">*</span></label>

    <%= f.text_field :last_name, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Email<span style="color:red;">*</span></label>

    <%= f.text_field :email, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Password<span style="color:red;">*</span></label>

    <%= f.password_field :password, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Confirm Password<span style="color:red;">*</span></label>

    <%= f.password_field :password_confirmation, class: 'form-control' %>

  </div>

  <div class="form-group">

    <button type="submit">Create Account</button>

  </div>

<% end %>

app/views/users/reinitialize.html.erb
<h1>Change Password</h1>

<%= form_for @user do |f| %>

  <div class="form-group">

    <label>Pasword</label>

    <%= f.password_field :password, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Confirm Password</label>

    <%= f.password_field :password_confirmation, class: 'form-control' %>

  </div>

  <div class="form-group">

    <button type="submit">Change password</button>

  </div>

<% end %>

app/views/users/show.html.erb
<h1>My Account</h1>

<h2>Account Info</h2>

<p> <%= @user.first_name %></p>
<p> <%= @user.last_name %></p>
<p> <%= @user.email %></p>

<h2>My Events</h2>

<% @events.each do |event| %>

  <p><%= event.title %></p>
  <p><a href="<%= event_path(event.id) %>" class="btn btn-primary">Show Event</a></p>

<% end %>

<p><a href="<%= edit_user_path %>" class="btn btn-primary">Edit my account</a></p>

<p><a href="<%= @user %>" class="btn btn-danger" data-confirm="Sure about this?" data-method="DELETE">Delete my account</a></p>

<p><a href="<%= new_event_path %>" class="btn btn-default">Add an event</a></p>